accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/<user_pk>/', views.profile, name='profile')
]

project_01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/',include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/update/', views.update, name='update'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

reviews/models.py
from django.db import models

# Create your models here.

class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=False)
    movie = models.CharField(max_length=80)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'content', 'movie',)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
# Create your views here.

def profile(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    context = {
        'user' : user,
    }
    return render(request, 'accounts/profile.html',context)

reviews/views.py
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm
# Create your views here.

def index(request):
    reviews = Review.objects.all()
    context = {
        'reviews':reviews,
    }
    return render(request, 'reviews/index.html',context)

def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)

    context = {
        'review' : review,
    }
    return render(request, 'reviews/detail.html',context)


def create(request):
    if request.method == "POST":
        pass
    else:
        form = ReviewForm()
    context ={
        'form' : form,
    }
    return render(request, 'reviews/create.html', context)

def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        pass
    else:
        form = ReviewForm(instance=review)
    context = {
        'review' : review,
        'form' : form,
    }
    return render(request, 'reviews/update.html', context)

def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    review.delete()
    return redirect('reviews:index')

reviews/templates/reviews/create.html
{% extends 'base.html' %}

{% block content %}
    <h3>CREATE</h3>
    <form action="{% url 'reviews:create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value='글 작성'>
    </form>
    <a href="{% url 'reviews:index' %}">BACK</a>
{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% block content %}
    <h3> DETAIL </h3>
    <p>
        작성자 - {{ review.user }}
    </p>
    <p>
        후기 번호 - {{ review.pk }}
    </p>
    <p>
        후기 제목 - {{ review.title }}
    </p>
    <p>
        후기 내용 - {{ review.content }}
    </p>
    <p>
        영화 이름 - {{ review.movie }}
    </p>

    <a href="{% url 'reviews:index' %}">BACK</a>
{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% block content %} 
    <div>
        <h3>
            {% comment %} 로그인된 유저 {% endcomment %}
            {{ user }} 님 안녕하세요!
        </h3>
    </div>
{% endblock content %}

reviews/templates/reviews/update.html
{% extends "base.html" %}
{% block content %}
  <h3>UPDATE</h3>
  <form action="{% url 'reviews:update' review.pk%}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="글 수정"></input>
  </form>
  <a href="{% url 'reviews:index' %}">BACK</a>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
    <div class="p-5">
      {% block content %}{% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

</html>